Jul-15 19:16:41.341 [main] DEBUG nextflow.cli.Launcher - $> /home/kevin/bin/nextflow run mnist.nf
Jul-15 19:16:41.435 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.24.4
Jul-15 19:16:41.442 [main] INFO  nextflow.cli.CmdRun - Launching `mnist.nf` [cocky_wilson] - revision: d3c44e7e6a
Jul-15 19:16:41.452 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: nextflow.config
Jul-15 19:16:41.454 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/kevin/MNIST_Nextflow/nextflow.config
Jul-15 19:16:41.715 [main] DEBUG nextflow.config.ConfigBuilder - Setting config profile: 'standard'
Jul-15 19:16:41.778 [main] DEBUG nextflow.Session - Session uuid: c122d40e-84b2-46a4-8fae-89bfe5d031c7
Jul-15 19:16:41.778 [main] DEBUG nextflow.Session - Run name: cocky_wilson
Jul-15 19:16:41.780 [main] DEBUG nextflow.Session - Executor pool size: 8
Jul-15 19:16:41.791 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 0.24.4 build 4341
  Modified: 22-05-2017 11:18 UTC (13:18 CEST)
  System: Linux 4.9.0-040900-generic
  Runtime: Groovy 2.4.10 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
  Encoding: UTF-8 (UTF-8)
  Process: 8454@kevin-XPS-15-9550 [127.0.1.1]
  CPUs: 8 - Mem: 15.5 GB (1.6 GB) - Swap: 14.6 GB (14.2 GB)
Jul-15 19:16:41.815 [main] DEBUG nextflow.Session - Work-dir: /home/kevin/MNIST_Nextflow/work [ext2/ext3]
Jul-15 19:16:41.816 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/kevin/MNIST_Nextflow/bin
Jul-15 19:16:41.890 [main] DEBUG nextflow.Session - Session start invoked
Jul-15 19:16:41.893 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Jul-15 19:16:41.893 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Jul-15 19:16:41.994 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-15 19:16:42.063 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-15 19:16:42.064 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-15 19:16:42.070 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-15 19:16:42.072 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Jul-15 19:16:42.076 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=15.5 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Jul-15 19:16:42.079 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Jul-15 19:16:42.079 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Jul-15 19:16:42.081 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Jul-15 19:16:42.162 [main] DEBUG nextflow.Session - >>> barrier register (process: runTensorflow)
Jul-15 19:16:42.175 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > runTensorflow -- maxForks: 8
Jul-15 19:16:42.207 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-15 19:16:42.208 [main] DEBUG nextflow.Session - Session await
Jul-15 19:16:42.308 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <runTensorflow> Poison pill arrived
Jul-15 19:16:42.312 [Actor Thread 2] DEBUG nextflow.processor.StateObj - <runTensorflow> State before poison: StateObj[submitted: 1; completed: 0; poisoned: false ]
Jul-15 19:16:42.418 [Actor Thread 3] INFO  nextflow.Session - [94/cd3045] Submitted process > runTensorflow
Jul-15 19:16:42.420 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <runTensorflow> After stop
Jul-15 19:16:46.126 [Thread-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'runTensorflow'

Caused by:
  Process `runTensorflow` terminated with an error exit status (1)

Command executed:

  python mnist.py --data_dir MNIST_data

Command exit status:
  1

Command output:
  MNIST_data
  Extracting MNIST_data/train-images-idx3-ubyte.gz
  Extracting MNIST_data/train-labels-idx1-ubyte.gz
  Extracting MNIST_data/t10k-images-idx3-ubyte.gz
  Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
  0.9162

Command error:
  2017-07-15 17:16:44.212695: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
  2017-07-15 17:16:44.212734: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
  2017-07-15 17:16:44.212740: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
  2017-07-15 17:16:44.212743: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
  2017-07-15 17:16:44.212747: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
  2017-07-15 17:16:44.305347: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
  2017-07-15 17:16:44.305670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
  name: GeForce GTX 960M
  major: 5 minor: 0 memoryClockRate (GHz) 1.0975
  pciBusID 0000:01:00.0
  Total memory: 1.96GiB
  Free memory: 1.55GiB
  2017-07-15 17:16:44.305684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
  2017-07-15 17:16:44.305714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
  2017-07-15 17:16:44.305721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
  Traceback (most recent call last):
    File "mnist.py", line 80, in <module>
      tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
    File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
      _sys.exit(main(_sys.argv[:1] + flags_passthrough))
    File "mnist.py", line 73, in main
      print (sess(config=tf.ConfigProto(log_device_placement=True)))
  TypeError: 'InteractiveSession' object is not callable

Work dir:
  /home/kevin/MNIST_Nextflow/work/94/cd304580403ae3d3fffecb3a72950c

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Jul-15 19:16:46.130 [Actor Thread 2] DEBUG nextflow.processor.TaskProcessor - <runTensorflow> Sending poison pills and terminating process
Jul-15 19:16:46.131 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: runTensorflow)
Jul-15 19:16:46.134 [Thread-1] DEBUG nextflow.Session - Session aborted -- Cause: Process `runTensorflow` terminated with an error exit status (1)
Jul-15 19:16:46.134 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-15 19:16:46.138 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-15 19:16:46.141 [Thread-1] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Jul-15 19:16:46.223 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jul-15 19:16:46.238 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
